org: andreidobre
app: auction
service: auction
frameworkVersion: '2 || 3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
