org: andreidobre
app: auction
service: auction-auth
frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  stage: ${opt:stage, 'dev'}}
  region: us-west-2
  runtime: nodejs14.x
  memorySize: 256
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
